language: go
go_import_path: github.com/mushiyu/go-mysql-server

env:
  global:
    - LD_LIBRARY_PATH="/usr/local/lib":${LD_LIBRARY_PATH}
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org

addons:
  apt:
    packages:
      - libmysqlclient-dev

matrix:
  fast_finish: true

before_script:
  - sudo service mysql stop

script:
  - make ci-script

jobs:
  include:
    - go: 1.11.x
    - go: 1.12.x

    # Integration test builds for 3rd party clients
    - go: 1.12.x
      script:
        - make TEST=go integration

    - language: python
      python: '3.6'
      before_install:
        - eval "$(gimme 1.12.4)"
      script:
        - make TEST=python-pymysql integration

    - language: php
      php: '7.1'
      before_install:
        - eval "$(gimme 1.12.4)"
      script:
        - make TEST=php integration

    - language: ruby
      ruby: '2.3'
      before_install:
        - eval "$(gimme 1.12.4)"
      script:
        - make TEST=ruby integration

    - language: java
      jdk: openjdk8
      before_install:
        - eval "$(gimme 1.12.4)"
      script:
        - make TEST=jdbc-mariadb integration

    - language: node_js
      node_js: '12'
      before_install:
        - eval "$(gimme 1.12.4)"
      script:
        - make TEST=javascript integration

    - language: csharp
      mono: none
      dotnet: '2.1'
      before_install:
        - eval "$(gimme 1.12.4)"
      script:
        - make TEST=dotnet integration

    - language: c
      compiler: clang
      before_install:
        - eval "$(gimme 1.12.4)"
      script:
        - make TEST=c integration
